name: My Bot
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install discord.py yt-dlp
      - name: Start Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
